FROM python:3.6-alpine

ENV FLASK_APP ui.py

COPY . /app
WORKDIR /app

RUN pip install --upgrade pip && \
    pip install -r requirements.txt -r requirements-test.txt

EXPOSE 8000

ENTRYPOINT [ "/bin/sh", "tests/test.sh" ]